spring.application.name=SimpleWeb

spring.datasource.username = Phenny
spring.datasource.password = mwaisaka

spring.datasource.url = jdbc:h2:mem:mwaisaka
spring.datasource.driverClassName = org.h2.Driver

spring.datasource.show-sql = true